spring:

  server:
    port: 80

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:mydb           # in-memory database
    # url=jdbc:h2:file:/data/demo   # file-based storage
    username: sa

  h2:
    console:
      enabled: true

