DROP TABLE IF EXISTS SCHOOL_DETAIL;
DROP TABLE IF EXISTS STUDENT_DETAIL;

CREATE TABLE SCHOOL_DETAIL (
  ID INT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  BOARD_NAME VARCHAR(250) NOT NULL
);

CREATE TABLE STUDENT_DETAIL (
  ID INT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  CLASS VARCHAR(250) NOT NULL,
  HOUSE VARCHAR(250) DEFAULT NULL,
  TOTAL_MARKS INT DEFAULT NULL,
  GRADE INT DEFAULT NULL,
  ROLL_NO INT DEFAULT NULL,
  SUBJECTS VARCHAR(250) NOT NULL,
  NICK_NAME VARCHAR(250) NOT NULL,
  SCHOOL_ID INT,
  FOREIGN KEY (SCHOOL_ID) references SCHOOL_DETAIL(ID)
);

INSERT INTO SCHOOL_DETAIL (ID, NAME, BOARD_NAME) VALUES
  (909, 'K V Lamphelpat', 'CBSE'),
  (808, 'K V Janakpuri', 'CBSE');

INSERT INTO STUDENT_DETAIL (ID, NAME, CLASS, HOUSE, TOTAL_MARKS, GRADE, ROLL_NO, SUBJECTS, NICK_NAME, SCHOOL_ID) VALUES
  (12345678, 'Mukesh', '12', 'Ashok', 100, 5, 2, 'maths, hindi', 'muku', 909),
  (12345679, 'Kusum', '10', 'Ashok', 300, 8, 1, 'english, sanskrit', 'rinki', 808);