DROP TABLE IF EXISTS STUDENT_DETAIL;
DROP TABLE IF EXISTS SCHOOL_DETAIL;

CREATE TABLE SCHOOL_DETAIL (
  ID INT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  BOARD_NAME VARCHAR(250) NOT NULL
);

CREATE TABLE STUDENT_DETAIL (
  ID INT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  CLASS VARCHAR(250) NOT NULL,
  HOUSE VARCHAR(250) DEFAULT NULL,
  TOTAL_MARKS INT DEFAULT NULL,
  GRADE INT DEFAULT NULL,
  ROLL_NO INT DEFAULT NULL,
  SUBJECTS VARCHAR(250) NOT NULL,
  NICK_NAME VARCHAR(250) NOT NULL,
  SCHOOL_ID INT,
  FOREIGN KEY (SCHOOL_ID) references SCHOOL_DETAIL(ID)
);